contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #maple channel"
    url: https://nfcore.slack.com/channels/maple
    about: Discussion about the nf-core/maple pipeline
